# Generated by Django 5.1.6 on 2025-03-11 06:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0005_delete_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/your_cloud_name/image/upload/v1631234567/default_image.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
