# Generated by Django 5.1.6 on 2025-03-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
