# Generated by Django 5.1.6 on 2025-03-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0014_reel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
