# Generated by Django 5.1.6 on 2025-03-20 05:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0016_remove_post_video_post_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
