# Generated by Django 5.1.6 on 2025-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'إعجاب'), ('comment', 'تعليق'), ('follow', 'متابعة'), ('mention', 'ذكر'), ('message', 'رسالة')], max_length=20),
        ),
    ]
