# Generated by Django 5.1.6 on 2025-03-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0024_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
