# Generated by Django 5.1.6 on 2025-03-27 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0028_alter_message_options_message_audio_message_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/your_cloud_name/image/upload/v1631234567/default_image.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
