# Generated by Django 5.1.6 on 2025-03-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0033_loggedinaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInAccount',
        ),
    ]
