# Generated by Django 5.1.6 on 2025-04-02 08:37

import socialmediaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0034_delete_loggedinaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[socialmediaapp.models.validate_no_html]),
        ),
    ]
